server:
  port: 8070

spring:
  application:
    name: 'eurekaserver'

management:
  endpoints:
    web:
      exposure:
        include: '*'

  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    hostname: 'localhost'

  client:
    service-url:
      defaultZone: 'http://localhost:8070/eureka/'

    fetch-registry: false
    register-with-eureka: false
