server:
  port: 8090

contact:
  name: mohammed aboulfadle
  email: mohammedaboulfadle@gmail.com


spring:
  application:
    name: 'orders'

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: orders

  config:
    import: 'optional:configserver:http://localhost:8071/'

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

  endpoint:
    shutdown:
      enabled: true

    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: 'http://localhost:8070/eureka/'

    fetch-registry: true
    register-with-eureka: true


resilience4j.circuitbreaker:
  instances:
    products:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 10
