server:
  port: 9010


spring:
  application:
    name: 'notifications'

  cloud:
    stream:
      bindings:
        confirmation:


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s